### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by corpetty** [Magicking/Clixplorer#1]
When attempting to build, I get the following error:

```
$ npm run build

> clixplorer@0.1.0 build /home/lucian/Clixplorer
> browserify -t brfs js/index.js -o js/bundle.js && for i in {index,tx,account,block}; do cat html/_header.html html/$i.html > $i.html; done

cat: html/_header.html: No such file or directory
cat: html/{index,tx,account,block}.html: No such file or directory
```

and it creates the file `{index,tx,account,block}.html` in the main directory, as if it isn't going through the loop in the browserify statement.  

I'm currently attempting this on the following system
- Ubuntu 17.04
- NodeJS v9.4.0
- npm v5.6.0

Any ideas?

**Comment by Magicking** [comment]
I guess the shell is not expanding the bracket list `{a,b}` to `["a" ,"b"]`, I should remove thoses.

Apparently you are also missing the `html/_header.html` file, see https://github.com/Magicking/Clixplorer/tree/master/html

Closing, please re-open if this still continue
